spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3310/ohiboard?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: ohi09563
    password: 58505850


  jpa:
    open-in-view: true
    hibernate:
     ddl-auto: update
     use-new-id-generate-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

    thymeleaf:
      cache: false